### ISSUE TITLE
Improve logging and error handling in CAFS concurrent reader

### ISSUE THREAD

**Issue by kerneltime** [oneconcern/datamon#207]
Hit this issue during a large download. The error path logging and handling needs to handle this gracefully.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x49e661]

goroutine 27527 [running]:
io.copyBuffer(0xd3c9c0, 0xc00caaee60, 0x0, 0x0, 0xc02c60e000, 0x8000, 0x8000, 0xd3d700, 0xc005d3bda0, 0x80)
    /usr/local/go/src/io/io.go:402 +0x101
io.Copy(...)
    /usr/local/go/src/io/io.go:364
github.com/oneconcern/datamon/pkg/cafs.(*chunkReader).WriteTo.func1(0xc000276340, 0xc00cc305a0, 0xc0000f6a00, 0x142c00000, 0x7fdfa9e1dfa0, 0xc00043e120, 0xa694ccd22d749d7a, 0x610313b3a61fc773, 0xf89c17f1cf751979, 0x5c1ea70f786918fb, ...)
    /datamon/pkg/cafs/reader.go:147 +0x20d
created by github.com/oneconcern/datamon/pkg/cafs.(*chunkReader).WriteTo
    /datamon/pkg/cafs/reader.go:138 +0x2aa
```

**Comment by kerneltime** [comment]
Other suggestions as improvements.

- [ ] Resumable downloads

- [ ] Retry in the CLI path
